version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - 127.0.0.1:1883:1883
      - 127.0.0.1:9005:9001
    restart: unless-stopped
